### ISSUE TITLE
Refactor tinlake.js

### ISSUE THREAD

**Issue by philipstanislaus** [centrifuge/tinlake.js#181]
- [ ] Migrate away from ethjs to ethers.io
- [ ] Use subscriptions for tx status instead of polling
- [ ] Change tinlake.js so it returns the txHash in a promise, e. g.:

```ts
interface pendingTx {
  txHash: string,
  contractKey:  string,
  timesOutAt: number
}
```

`const pendingTx = await tinlake.transfer(addr, amount, timesOutAt = DEFAULT_TIMEOUT)`
`const receipt = await getTransactionReceipt(pendingTx)`
`subscribeStatus(pendingTx, () => {})`

`getTransactionReceipt`, `subscribeStatus` should reject directly if timesOutAt is in the past

**Comment by offerijns** [comment]
We decided not to implement `subscribeStatus()` for now, until we find a specific need for it.
